// src/components/article-preview/index.tsx
import React from 'react';
import { Link } from 'gatsby';

import * as styles from './styles.module.scss';

import { ArticleTag } from '../article-tag';

interface ArticlePreviewProps {
  title: string;
  tags: string[];
  published: string;
  updated: string;
  timeToRead: Number;
  slug: string;
  excerpt: string;
}

export const ArticlePreview: React.FC<ArticlePreviewProps> = (props) => {
  return (
    <article className={styles.article}>
      <header>
        <Link to={props.slug}>
          <h3>{props.title}</h3>
        </Link>
        <div className={styles.article__tags}>
          {props.tags.map((tag) => {
            return <ArticleTag tag={tag} key={tag} />;
          })}
        </div>
        <div className={styles.article__datetime}>
          <time dateTime={props.published}>
            {props.published} <em>(oppdatert {props.updated})</em>
          </time>
          <div>
            ca. {props.timeToRead} minutt{+props.timeToRead > 1 ? 'er' : ''} med
            lesestoff
          </div>
        </div>
      </header>
      <section className={styles.article__intro}>
        <p>
          {props.excerpt}{' '}
          <Link className={styles.article__read_more} to={props.slug}>
            <strong>[ ... ]</strong>
          </Link>
        </p>
      </section>
    </article>
  );
};

// src/app/home/article-preview/article-preview.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'mks-article-preview',
  templateUrl: './article-preview.component.html',
  styleUrls: ['./article-preview.component.scss'],
})
export class ArticlePreviewComponent implements OnInit {
  @Input() postData: any;
  constructor() {}

  ngOnInit(): void {}
}

<article class="article">
  <header>
    <h3>{{ postData.title }}</h3>

    <div class="article__tags">
      <div class="article__tag" *ngFor="let tag of postData.tags">
        {{ tag }}
      </div>
    </div>
    <div class="article__datetime">
      <time [dateTime]="postData.date">{{ postData.date }}</time>
      <div class="article__read-time">
        ca. {{ postData.readTime }} minutter med lesestoff
      </div>
    </div>
  </header>
  <section class="article__intro">
    <p>
      {{ postData.description
      }}<a
        [routerLink]="[postData.route]"
        routerLinkActive="router-link-active"
        class="article__read-more"
        href="/"
        ><strong>[...]</strong></a
      >
    </p>
  </section>
</article>
